-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--


ENTITY Top_tb IS
-- Declarations

END Top_tb ;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;

ARCHITECTURE struct OF Top_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clock           : STD_LOGIC;
   SIGNAL key_1           : STD_LOGIC;
   SIGNAL key_2           : STD_LOGIC;
   SIGNAL key_3           : STD_LOGIC;
   SIGNAL enable          : STD_LOGIC;
   SIGNAL SW_in           : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL reset           : STD_LOGIC;


   -- Component Declarations
	COMPONENT Top IS
		
		GENERIC ( N : positive := 8); --10 for Quartus 8 for modelsim
		PORT( reset, clock, enable			: IN 	STD_LOGIC; 
			LEDR_out                  		: OUT   STD_LOGIC_VECTOR(7 DOWNTO 0);
			HEX0_out               			: OUT   STD_LOGIC_VECTOR(6 DOWNTO 0);
			HEX1_out               			: OUT   STD_LOGIC_VECTOR(6 DOWNTO 0);
			HEX2_out               			: OUT   STD_LOGIC_VECTOR(6 DOWNTO 0);
			HEX3_out               			: OUT   STD_LOGIC_VECTOR(6 DOWNTO 0);
			HEX4_out               			: OUT   STD_LOGIC_VECTOR(6 DOWNTO 0);
			HEX5_out               			: OUT   STD_LOGIC_VECTOR(6 DOWNTO 0);
			key_1                           : IN    STD_LOGIC;
			key_2                           : IN    STD_LOGIC;
			key_3                           : IN    STD_LOGIC;
			SW_in                           : IN   STD_LOGIC_VECTOR(7 DOWNTO 0)
			);
	END 	COMPONENT;
   
   
	COMPONENT Top_tester IS
	   PORT( 

		  key_1           : OUT    STD_LOGIC;
		  key_2           : OUT    STD_LOGIC;
		  key_3           : OUT    STD_LOGIC;
		  SW_in           : OUT   STD_LOGIC_VECTOR(7 DOWNTO 0);
		  clock           : OUT    STD_LOGIC;
		  reset           : OUT    STD_LOGIC
	   );

	-- Declarations

	END COMPONENT ;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Top USE ENTITY work.Top;
   FOR ALL : Top_tester USE ENTITY work.Top_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Top
      PORT MAP (
         reset           => reset,
         clock           => clock,
		 enable          => '1',
		 key_1           => key_1,
		 key_2           => key_2,
		 key_3           => key_3,
		 SW_in           => SW_in
      );
   U_1 : Top_tester
      PORT MAP (
		 key_1           => key_1,
		 key_2           => key_2,
		 key_3           => key_3,
		 SW_in           => SW_in,
         clock           => clock,
         reset           => reset
      );

END struct;
